# Generated by Django 2.0.2 on 2018-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_cham', models.CharField(max_length=150)),
                ('data_cham', models.DateTimeField()),
                ('solicitante_cham', models.CharField(max_length=30)),
                ('msg_cham', models.CharField(max_length=400)),
                ('status_cham', models.SmallIntegerField()),
            ],
        ),
    ]
