# Generated by Django 2.0.2 on 2018-02-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supllier',
            new_name='Supplier',
        ),
    ]
