# Generated by Django 2.0.2 on 2018-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20180220_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adress',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
